apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('update_item/<int:item_id>/', views.update_item, name='update_item'),
    path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
    path('checkout/', views.checkout, name='checkout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('other/', include('apps.common.urls')),
    path('other/', include('apps.test_app.urls')),
    path('other/cart/', include('apps.cart.urls')),
    path('', include('apps.home.urls')),
    path('cart/', include('apps.cart_shop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('login/', include('apps.auth_shop.urls')),
]

apps/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user}'


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='static/products/',
                              null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        img = img.resize((100, 100), Image.ANTIALIAS)
        img.save(self.image.path)

    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.cart}_{self.product}'

apps/cart/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem


def view_cart(request):
    cart_items = CartItem.objects.filter(cart__user=request.user)
    total_price = sum(
        item.product.price * item.quantity for item in cart_items)
    context = {'cart_items': cart_items, 'total_price': total_price}
    return render(request, 'cart/cart.html', context)


def update_item(request, item_id):
    item = CartItem.objects.get(id=item_id)
    item.quantity += int(request.GET.get('quantity'))
    item.save()
    return redirect('cart:view_cart')


def remove_item(request, item_id):
    CartItem.objects.filter(id=item_id).delete()
    return redirect('cart:view_cart')


def checkout(request):
    return redirect('cart:view_cart')

apps/cart/templates/cart/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <table>
   <thead>
       <tr>
           <th>Product</th>
           <th>Price</th>
           <th>Pic</th>
           <th>Quantity</th>
           <th>Total</th>
           <th>Actions</th>
       </tr>
   </thead>
   <tbody>
       {% for item in cart_items %}
           <tr>
               <td>{{ item.product.name }}</td>
               <td>{{ item.product.price }}</td>
               <td><img src="{{ item.product.image.url }}" alt="{{ item.product.name }}"></td>
               <td>{{ item.quantity }}</td>
               <td>{% widthratio item.product.price 1 item.quantity %}</td>
               <td>
                   <a href="{% url 'cart:update_item' item.id %}?quantity=1">+</a>
                   <a href="{% url 'cart:update_item' item.id %}?quantity=-1">-</a>
                   <a href="{% url 'cart:remove_item' item.id %}">Remove</a>
               </td>
           </tr>
       {% endfor %}
   </tbody>
   <tfoot>
       <tr>
           <td colspan="3"></td>
           <td>Total: {{ total_price }}</td>
           <td><a href="{% url 'cart:checkout' %}">Checkout</a></td>
       </tr>
   </tfoot>
</table>
</head>
<body>

</body>
</html>